### ISSUE TITLE
ClassNotFoundException: java.time.temporal.ChronoUnit

### ISSUE THREAD

**Issue by jmckitrick** [jeffmad/clj-icalendar#1]
I get this error running `lein test` in the repo, and when trying to use the library.

{:type clojure.lang.Compiler$CompilerException
   :message java.lang.ClassNotFoundException: java.time.temporal.ChronoUnit, compiling:(clj_icalendar/core.clj:41:7)
   :at [clojure.lang.Compiler analyze Compiler.java 6543]}

**Comment by jmckitrick** [comment]
@jeffmad is this library still being maintained?  I'd love to use it for a current project.

**Comment by jeffmad** [comment]
Hi Jonathon,
I have completed what I want to do with it and have no more features
planned, but certainly am open to changes and can answer questions.
The purpose for which  I wrote it is for my own project - our users can
have a calendar subscription to the "events" they purchase - so one of my
fundamental assumptions is that users don't directly create events, and it
is a PUBLISHED calendar, not something with adds/cancels/accept/decline.
 (Just so you know where I was coming from).

I decided to use ical4j because it seems mature, seems to care deeply about
meeting the ical spec, and has decent documentation.   I looked at some of
the other clojure ical libraries and they did not seem very complete,
lacking examples, documentation, etc.

This was my first clojure library (a goal of mine),  and I am sure that it
can be improved to support more general use cases, but I stopped where it
meets my needs. For example, a lot of extra properties can be added to an
event, but I only made it possible to use the subset that I needed.
Reading the ical spec is not much fun, it seems quite complicated.

Hope this helps,
--jeff

**Comment by jeffmad** [comment]
I will take a look at the broken test.

**Comment by jeffmad** [comment]
hmm, could it be that you are using < java 1.8?  I started with java 1.8 to make life easier for myself because of the new Date Time API and not wanting to depend on clj-time

**Comment by jmckitrick** [comment]
That would be the problem.  I'm using 1.7.  Short of upgrading, is there a
library I could include and I shim I could write that would hold me over
until I upgrade?

**Comment by jeffmad** [comment]
Ok, Let me know if this works for you. I think you can fork the github
project,
go into src/clj-icalendar/core.clj

look in method truncate-time, and replace the threading macro with the let
block below.  That seems to be the only usage of Java 8.
- I only tested on the REPL

After that, you can do lein uberjar and mvn install install into your local
.m2

(defn- truncate-time
  "function to take a java.util.Date object and return a date
   with the time portion truncated."
  [^Date d](-> d
      .toInstant
      %28.truncatedTo java.time.temporal.ChronoUnit/DAYS%29
      Date/from))

(let [d (java.util.Date. (System/currentTimeMillis))
        c (doto (java.util.Calendar/getInstance)
            (.setTime d)
            (.set java.util.Calendar/HOUR_OF_DAY 0)
            (.set java.util.Calendar/MINUTE 0)
            (.set java.util.Calendar/SECOND 0)
            (.set java.util.Calendar/MILLISECOND 0))](.getTime c))

**Comment by jmckitrick** [comment]
I'll give that a shot, but I need to make sure I can deploy the same
version to Heroku for production.

**Comment by jeffmad** [comment]
if you use lein uberjar it will pick it up locally.  if that doesn't work,
i will patch it and bump the version.  I am a bit crunched for time is the
only reason I wouldn't just do it outright for you.

**Comment by jmckitrick** [comment]
I appreciate it, but it's not time critical.  I'll use it when it's ready.  Thanks!

**Comment by jeffmad** [comment]
Jon,

[clj-icalendar "0.1.3"]   i changed core.clj to use java Calendar instead
of java.time.  However the tests will still fail because they are still
using java.time from 1.8.  I'd need to add a dependency to joda-time to fix
that, and it is too much trouble for me at this point.

**Comment by jmckitrick** [comment]
@jeffmad I'll take it from here, thanks!
